_target_: pinnsjax.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 10

enable_progress_bar: true

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1
