# GPU 环境版本 - 适用于 CUDA 支持的机器
name: pinnsgpu

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.8.*
  - hydra-core=1.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  - pip>=23
  - pip:
      - nvidia-cudnn-cu11==8.6.0.163
      - tensorflow==2.13.*
      - jax[cuda]>=0.4.13
      - flax>=0.7.0
      - optax>=0.1.7
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
      - PyDOE
      - scipy
      - matplotlib
      - tqdm
