# CPU 环境版本 - 适用于 Mac 和没有 GPU 的机器
name: pinnscpu

channels:
  - conda-forge
  - defaults

dependencies:
  - hydra-core=1.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  - pip>=23
  - pip:
      - tensorflow==2.13.*
      # 对于 M 系列芯片的 Mac 用户，如需优化可取消下面两行注释
      # - tensorflow-macos>=2.13.0
      # - tensorflow-metal>=1.0.0
      - jax[cpu]>=0.4.13
      - flax>=0.7.0
      - optax>=0.1.7
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
      - PyDOE
      - scipy
      - matplotlib
      - tqdm
