# @package _global_

# 在此处指定默认配置
# 默认值的顺序决定了配置相互覆盖的顺序
defaults:
  - _self_
  - data: default
  - model: default
  - net: default
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  - hparams_search: null

  # 可选的本地配置，用于特定机器/用户设置
  # 这是可选的，因为它不需要存在且被排除在版本控制之外
  - optional local: default

# 任务名称，决定输出目录路径
task_name: "train"

dtype: float32

# 标签，帮助您识别您的实验
# 您可以在实验配置中覆盖这些标签
# 从命令行使用 `python train.py tags="[first_tag, second_tag]"` 覆盖
tags: ["dev"]

# 设置为 False 可跳过模型训练
train: True

# 使用训练期间获得的最佳模型权重，在测试集上评估
# lightning 根据检查点回调中指定的指标选择最佳权重
test: False

# 只需提供检查点路径即可恢复训练
ckpt_path: null

# pytorch、numpy 和 python.random 中随机数生成器的种子
seed: 1234
